# -*- coding: utf-8 -*-
#
# This file is covered by the LICENSING file in the root of this project.
#

### Dockerfile for open-hacnathon(client)
### based on python official image

FROM python:3.7-alpine

USER root

#logs
RUN mkdir -p /var/log/open-hackathon/
#client
RUN mkdir -p /opt/open-hackathon/open-hackathon-client

COPY ./open-hackathon-client /opt/open-hackathon/open-hackathon-client

#pip
RUN pip install -r /opt/open-hackathon/open-hackathon-client/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir

#config
RUN mv /opt/open-hackathon/open-hackathon-client/src/client/config_docker.py /opt/open-hackathon/open-hackathon-client/src/client/config.py

#init
COPY ./deploy/hackathon-docker/docker-entrypoint-client.sh /opt/open-hackathon

RUN chmod 777 /opt/open-hackathon/docker-entrypoint-client.sh && \
    dos2unix /opt/open-hackathon/docker-entrypoint-client.sh

EXPOSE 80

ENTRYPOINT ./opt/open-hackathon/docker-entrypoint-client.sh