# -*- coding: utf-8 -*-
#
# This file is covered by the LICENSING file in the root of this project.
#

### Dockerfile for open-hacnathon(server)
### based on python official image

FROM python:3.7-alpine

USER root

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk update && \
    apk add --no-cache g++ gcc musl-dev libxslt-dev
#logs
RUN mkdir -p /var/log/open-hackathon/
# server
RUN mkdir -p /opt/open-hackathon/open-hackathon-server
COPY ./open-hackathon-server /opt/open-hackathon/open-hackathon-server
#config
RUN cp /opt/open-hackathon/open-hackathon-server/src/hackathon/config_docker.py /opt/open-hackathon/open-hackathon-server/src/hackathon/config.py
#init
COPY ./deploy/hackathon-docker/docker-entrypoint-server.sh /opt/open-hackathon

RUN chmod 777 /opt/open-hackathon/docker-entrypoint-server.sh && \
    dos2unix /opt/open-hackathon/docker-entrypoint-server.sh

RUN pip install -r /opt/open-hackathon/open-hackathon-server/requirements.txt

ENTRYPOINT ./opt/open-hackathon/docker-entrypoint-server.sh
