# -*- coding: utf-8 -*-
#
# This file is covered by the LICENSING file in the root of this project.
#

### Dockerfile for open-hacnathon(server)
### based on python official image

FROM python:3.6-alpine

USER root

RUN mkdir -p /var/log/open-hackathon/ \
    && mkdir -p /opt/open-hackathon/open-hackathon-server


RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk update && \
    apk add --no-cache g++ gcc musl-dev libxslt-dev

COPY ./open-hackathon-server/requirements.txt /opt/open-hackathon/open-hackathon-server

### RUN pip install -r /opt/open-hackathon/open-hackathon-server/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir
RUN pip install -r /opt/open-hackathon/open-hackathon-server/requirements.txt

COPY ./open-hackathon-server /opt/open-hackathon/open-hackathon-server

WORKDIR /opt/open-hackathon/open-hackathon-server/src
CMD ["gunicorn", "-w", "5", "-b", "0.0.0.0:15000", "hackathon:app"]

EXPOSE 15000
