repo:
  - ./*

# Add 'document' to any changes within 'document' folder or any subfolders
document:
  - documents/*
  - documents/**/*

deploy:
  - deploy/*
  - deploy/**/*
  - src/deploy/*
  - src/deploy/**/*

oph-client:
  - open-hackathon-client/*
  - open-hackathon-client/**/*

oph-server:
  - open-hackathon-server/*
  - open-hackathon-server/**/*

oph-server-v2:
  - src/open-hackathon-server/*
  - src/open-hackathon-server/**/*
