Sample_Courses = [
    {
        "id": "flask",
        "name": "Python+Flask",
        "create_time": "2014-10-25",
        "like_count": 1330,
        "description": "Python on Flask",
        "tags": ["python", "flask", "web", "web framework", "python web framework","language"],
        "recommend":3,
        "image":"/static/pic/python.jpg",
        "share_count":1123,
        "studying_count":11,
        "studied_count":223
    },
    {
        "id": "django",
        "name": "Python+Django",
        "create_time": "2014-10-25",
        "like_count": 10,
        "description": "Python on Django",
        "tags": ["python", "django", "web", "web framework", "python web framework", "MVC", "mvc framework","language"],
        "recommend":4,
        "image":"/static/pic/python.jpg",
        "share_count":324,
        "studying_count":2,
        "studied_count":14
    },
    {
        "id": "pyramid",
        "name": "Python+Pyramid",
        "create_time": "2014-10-25",
        "like_count": 320,
        "description": "Python on Pyramid",
        "tags": ["python", "pyramid", "web", "web framework", "python web framework","language"],
        "recommend":1,
        "image":"/static/pic/python.jpg",
        "share_count":474,
        "studying_count":146,
        "studied_count":87
    },
    {
        "id": "tornado",
        "name": "Python+Tornado",
        "create_time": "2014-10-25",
        "like_count": 130,
        "description": "Python on Tornado",
        "tags": ["python", "tornado", "web", "web framework", "python web framework"],
        "recommend":3,
        "image":"/static/pic/python.jpg",
        "share_count":276,
        "studying_count":54,
        "studied_count":75
    },
    {
        "id": "beego",
        "name": "Go+Beego",
        "create_time": "2014-10-25",
        "like_count": 303,
        "description": "GO on Beego",
        "tags": ["go", "golang", "beego", "web framework", "golang web framework", "web"],
        "recommend":4,
        "image":"/static/pic/go.jpg",
        "share_count":324,
        "studying_count":2,
        "studied_count":14
    },
    {
        "id": "rails",
        "name": "Ruby+Rails",
        "create_time": "2014-10-25",
        "like_count": 23,
        "description": "Ruby on Rails",
        "tags": ["ruby", "rails", "web", "web framework", "ruby web framework", "MVC", "mvn framework","language"],
        "recommend":5,
        "image":"/static/pic/ruby.jpg",
        "share_count":2693,
        "studying_count":1456,
        "studied_count":153
    },
    {
        "id": "sinatra",
        "name": "Ruby+Sinatra",
        "create_time": "2014-10-25",
        "like_count": 30,
        "description": "Ruby on Sinatra",
        "tags": ["ruby", "sinatra", "web", "web framework", "ruby web framework"],
        "recommend":4,
        "image":"/static/pic/ruby.jpg",
        "share_count":2533,
        "studying_count":841,
        "studied_count":53
    },
    {
        "id": "mean",
        "name": "JavaScript+MEAN",
        "create_time": "2014-10-25",
        "like_count": 10,
        "description": "Javascript + MEAN",
        "tags": ["javascript", "MEAN", "MongoDB", "ExtJS", "AngularJS", "web framework", "javascript web framework", "node web framework", "MVC", "mvc framework", "web","language"],
        "recommend":3,
        "image":"/static/pic/javascript.jpg",
        "share_count":981,
        "studying_count":81,
        "studied_count":13
    },
    {
        "id": "spring",
        "name": "Java+Spring",
        "create_time": "2014-10-25",
        "like_count": 330,
        "description": "Java and Spring",
        "tags": ["java", "spring", "ssh", "hibernate", "struts", "web", "web framework", "java web framework", "MVC", "java mvc framework","language"],
        "recommend":5,
        "image":"/static/pic/java.jpg",
        "share_count":4386,
        "studying_count":881,
        "studied_count":513
    },
    {
        "id": "play",
        "name": "Scala+Play",
        "create_time": "2014-10-25",
        "like_count": 30,
        "description": "Scala and Play",
        "tags": ["scala", "Play", "web", "web framework", "scala web framework"],
        "recommend":1,
        "image":"/static/pic/scala.jpg",
        "share_count":176,
        "studying_count":13,
        "studied_count":5
    },
    {
        "id": "jstorm",
        "name": "jStorm",
        "create_time": "2014-10-25",
        "like_count": 30,
        "description": "jStorm",
        "tags": ["jstorm", "storm", "realtime analytics", "stream analytics", "big data", "noSQL"],
        "recommend":3,
        "image":"/static/pic/jstorm.jpg",
        "share_count":689,
        "studying_count":145,
        "studied_count":58
    },
    {
        "id": "storm",
        "name": "Storm",
        "create_time": "2014-10-25",
        "like_count": 30,
        "description": "Storm",
        "tags": ["storm", "realtime analytics", "stream analytics", "big data", "noSQL"],
        "recommend":2,
        "image":"/static/pic/storm.gif",
        "share_count":314,
        "studying_count":96,
        "studied_count":58
    },
    {
        "id": "mdrill",
        "name": "mDrill",
        "create_time": "2014-10-25",
        "like_count": 30,
        "description": "mDrill",
        "tags": ["mdrill", "ad hoc analytics", "interactive analytics", "big data", "noSQL"],
        "recommend":1,
        "image":"/static/pic/alibaba.jpg",
        "share_count":178,
        "studying_count":11,
        "studied_count":13
    },
    {
        "id": "kafka",
        "name": "Kafka",
        "create_time": "2014-10-25",
        "like_count": 30,
        "description": "Kafka",
        "tags": ["kafka", "message queue", "distributed message queue"],
        "recommend":1,
        "image":"/static/pic/kafka.jpg",
        "share_count":312,
        "studying_count":56,
        "studied_count":31
    },
    {
        "id": "spark",
        "name": "Spark/Shark",
        "create_time": "2014-10-25",
        "like_count": 30,
        "description": "Spark/Shark",
        "tags": ["spark", "shark", "in-memory big dta", "in-memory hadoop", "interactive analytics", "big data", "noSQL"],
        "recommend":1,
        "image":"/static/pic/spark.png",
        "share_count":89,
        "studying_count":7,
        "studied_count":11
    },
    {
        "id": "hadoop",
        "name": "Hadoop",
        "create_time": "2014-10-25",
        "like_count": 30,
        "description": "hadoop",
        "tags": ["hadoop", "noSQL", "map reduce", "big data", "hive", "pig", "yarn", "hdfs", "hbase", "batch processing"],
        "recommend":3,
        "image":"/static/pic/hadoop.png",
        "share_count":442,
        "studying_count":73,
        "studied_count":93
    }
]
